// Generated by Melange

import * as React from "@remix-run/react";
import * as Curry from "melange.js/curry.js";
import * as React$1 from "react";
import * as JsxRuntime from "react/jsx-runtime";

function MovieLink$default(Props) {
  var movie = Props.movie;
  var match = React$1.useState(function () {
        return "intent";
      });
  var setPrefetch = match[1];
  var prefetch = match[0];
  var movieId = movie.id;
  React$1.useEffect((function () {
          var item = sessionStorage.getItem("movie-" + movieId);
          if (!(item == null)) {
            Curry._1(setPrefetch, (function (param) {
                    return "none";
                  }));
          }
          return (function (param) {
                    
                  });
        }), []);
  var prefetchImage = function (param) {
    if (prefetch === "none") {
      return ;
    }
    var image = new Image();
    image.src = movie.thumbnail;
  };
  return JsxRuntime.jsx(React.Link, {
              to: "/movie/" + movieId,
              prefetch: prefetch,
              onMouseEnter: prefetchImage,
              onFocus: prefetchImage,
              children: movie.title
            });
}

var $$default = MovieLink$default;

export {
  $$default as default,
}
/* @remix-run/react Not a pure module */
